services:
  #tasks:
  #  image: email_scheduler/quatz_project:1.0
  #  build:
  #    context: ./
  #    dockerfile: src/main/docker/Dockerfile.${QUARKUS_MODE:-jvm}
  #  environment:
  #    - QUARKUS_DATASOURCE_USERNAME=email_scheduler_username
  #    - QUARKUS_DATASOURCE_PASSWORD=email_scheduler_password
  #    - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://postgres:5432/email_scheduler
  #  networks:
  #    - tasks-network
  #  depends_on:
  #    postgres:
  #      condition: service_healthy

  #nginx:
  #  image: nginx:1.17.6
  #  volumes:
  #    - ./nginx.conf:/etc/nginx/nginx.conf:ro
    #depends_on:
    #  - tasks
  #  ports:
  #    - 8080:8080
  #  networks:
  #    - tasks-network

  postgres:
    image: postgres:14.1
    container_name: quarkus_test
    environment:
      - POSTGRES_USER=email_scheduler_username
      - POSTGRES_PASSWORD=email_scheduler_password
      - POSTGRES_DB=email_scheduler
    ports:
      - 5432:5432
    networks:
      - tasks-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U email_scheduler_username -d email_scheduler" ]
      interval: 10s
      timeout: 5s
      retries: 5
networks:
  tasks-network:
    driver: bridge